spring.application.name=biblioteca-web
server.port=8080

# MongoDB Atlas (Cluster0) via variavel de ambiente para nao expor senha no codigo
spring.data.mongodb.uri=${MONGODB_URI:mongodb+srv://drailom256_db_user:jdCaunBJzNA2qqb9@cluster0.4d1ledt.mongodb.net/biblioteca?retryWrites=true&w=majority&appName=Cluster0&connectTimeoutMS=3000&socketTimeoutMS=3000&serverSelectionTimeoutMS=3000}

spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

server.error.whitelabel.enabled=false
server.error.include-message=never
server.error.include-stacktrace=never
